### ISSUE TITLE
All Routes Display Not Found

### ISSUE THREAD

**Issue by kenlittleton** [app-generator/flask-black-dashboard#2]
After installing without problems and running successfully, the only page that renders regardless of url is the 404 page with:
```
The URL you were looking for does not seem to exist.
Define the new page in /pages
```
Had to delete **"SERVER_NAME"** from _configuration.py_ to fix this issue.
https://stackoverflow.com/questions/24437248/unexplainable-flask-404-errors

**Comment by bryanmullinbwp** [comment]
I had to run an NPM install to get things to show. Just adding this for people that might stumble across.
