### ISSUE TITLE
Web app doesn't load after installation

### ISSUE THREAD

**Issue by bryanmullinbwp** [app-generator/flask-black-dashboard#3]
After following the installation steps on a windows dev machine, the flask server launches, and when you load 127.0.0.1:5000, the server responds with this:
"127.0.0.1 - - [19/Nov/2019 12:39:33] "GET / HTTP/1.1" 302 -"

but then nothing ever loads, it will just sit and spin. Any ideas?

**Comment by app-generator** [comment]
Hello @bryanmullinbwp, 
I will migrate the app to a newer boilerplate structure. The current design pattern is deprecated.
