### ISSUE TITLE
Where is the data?

### ISSUE THREAD

**Issue by sergiolucero** [app-generator/flask-black-dashboard#4]
Great project but I fail to find where the data is read from. Also, it took me a while to figure out where to place my Google Maps API credentials. Perhaps these things could be more obvious from the go.

Javascript experts would trivially figure this one out, but I'm a Python guy!

**Comment by sergiolucero** [comment]
Found it at app/base/static/assets/demo/demo.js

**Comment by app-generator** [comment]
Hello @sergiolucero, 
Still, need help with this? Feel free to join us on [Discord](https://discord.gg/fZC6hup)
