### ISSUE TITLE
Not loading the CSS file

### ISSUE THREAD

**Issue by fhassan-ui** [app-generator/flask-black-dashboard#7]
![github](https://user-images.githubusercontent.com/82574760/160071499-411d822f-56f4-4a0b-ba3b-97222d8062fc.PNG)

I tried to run the code by using the README. Able to run the application but the CSS file is not reflecting. Screenshot of UI attached. Can anyone know what is the exact reason for this issue. Any help is appreciated. Thanks

**Comment by app-generator** [comment]
Hello @fhassan-ui 

Sorry for this late reply. Somehow your message landed in the SPAM folder. 
Just tested the project in Windows / Linux and Docker. All looks good. 

Can you inspect your browser to see why the assets are blocked? 

P.S. Ty for using our products.

**Comment by fhassan-ui** [comment]
When I inspect the browser this file **/static/assets/css/black-dashboard.css?v=1.0.0** is not loading in my application.

**Comment by app-generator** [comment]
Hello @fhassan-ui, 

Please test using the latest version. For more options, configure the project via the LIVE generator: 

https://appseed.us/generator/black-dashboard/
