### ISSUE TITLE
Bad gateway 502

### ISSUE THREAD

**Issue by WhiTExB3AR** [app-generator/flask-black-dashboard#8]
I have a problem when build app in Ubuntu 20.04 by Docker 20.10.14 and Docker Compose is 1.25.0 as 2 pictures below.

![image](https://user-images.githubusercontent.com/62128227/160554482-b4024ff5-2410-4e0b-b70e-5ab432b575c8.png)

![image](https://user-images.githubusercontent.com/62128227/160554557-b5bf9c0b-fe8d-4e41-bba7-136c35061ce7.png)

**Pre-produced:**
1. Clone the latest version 1.0.6 
```
$ git clone https://github.com/app-generator/flask-black-dashboard.git
$ cd flask-black-dashboard
```
2. Build from docker-compose
$ docker-compose up --build -d

3. Error version
![image](https://user-images.githubusercontent.com/62128227/160555666-c55e4083-0f8e-4ea1-ae02-824581b0576b.png)

4. Change from version 3.8 to version: 3.3 in line 1 of docker-compose.yml

5. Run step 2 again 
![image](https://user-images.githubusercontent.com/62128227/160556009-f65ba7c5-c653-43f2-b2f9-21e48b50dc9d.png)

6. Visit http://localhost:85
![image](https://user-images.githubusercontent.com/62128227/160556212-93c0a5ac-933a-4074-8464-147b40bb486a.png)

**Comment by tsoarescruz** [comment]
To fix this problem, you need to change the port in the fileappseed_app.conf like this:

```
upstream webapp {
    server appseed_app:85;
}

server {
    listen 85;
    server_name localhost;

    location / {
        proxy_pass http://webapp;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
    }

}

```

**Comment by app-generator** [comment]
@tsoarescruz Ty for your fix!
@WhiTExB3AR can we close the issue?

**Comment by WhiTExB3AR** [comment]
Sure, thank for your help 🥰
